CREATE TABLE IF NOT EXISTS users
(
    id        INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(30) NOT NULL,
    email     VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    item_name    VARCHAR(50)  NOT NULL,
    description  VARCHAR(200) NOT NULL,
    is_available BOOLEAN      NOT NULL,
    owner_id     INTEGER      NOT NULL REFERENCES users (id),
    request_id   INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id           INTEGER                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comment_text VARCHAR(200)                NOT NULL,
    item         INTEGER                     NOT NULL REFERENCES items (id),
    author       INTEGER                     NOT NULL REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    INTEGER                     NOT NULL REFERENCES items (id),
    booker_id  INTEGER                     NOT NULL REFERENCES users (id),
    status     VARCHAR(8)                  NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id          INTEGER                     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(200)                NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author      INTEGER                     NOT NULL REFERENCES users (id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);